### ISSUE TITLE
getElement is used and Cannot add Field like this (use addField Exception)

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [atk4/report#30]
https://github.com/atk4/report/blob/8ed1b4bfb24714c48da834557717e090e06dc5c8/src/GroupModel.php#L129

Need to use getField but doing that is getting the second issue: Exception from data/src/Model@add method 
'You should always use addField() ...'

PS. getElement is also used in other places in report repo.

**Comment by romaninsh** [comment]
i think those issues are unrelated but both have to be fixes.

**Comment by DarkSide666** [comment]
To be compatible with new atk4/data versions we have to replace `getElement` with `getField`.

**Comment by gowrav-vishwakarma** [comment]
Done the replacing and created a pull request, for now just in GroupModel. But still, the marked line has issues.
